name: Deploy to OVH Onchain

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
      
    - name: Sync files to OVH via SCP/SFTP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.OVH_FTP_SERVER }}
        username: ${{ secrets.OVH_FTP_USERNAME }}
        password: ${{ secrets.OVH_FTP_PASSWORD }}
        port: 22
        source: "./*"
        target: "/home/wxejrxt/onchain"
